<a href="https://colab.research.google.com/github/raviiraj13/Python/blob/main/Numpyp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5,6,7])
print(arr_1d)

[1 2 3 4 5 6 7]


In [4]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


#List vs Numpy Array

In [6]:
py_list=[1,2,3]
print(py_list*2)

[1, 2, 3, 1, 2, 3]


In [7]:
numpy_arr=np.array([1,2,3])
print(numpy_arr * 2)

[2 4 6]


#Creating new arrays

In [8]:
zeroes=np.zeros((3,4))
print(zeroes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
ones=np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
full=np.full((3,4),5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [12]:
random=np.random.random((3,4))
print(random)

[[0.09489622 0.91223378 0.1766636  0.374495  ]
 [0.20484506 0.07022924 0.31945255 0.66090641]
 [0.69135153 0.0361951  0.58679538 0.93454362]]


In [13]:
sequence=np.arange(1,10,2)
print(sequence)

[1 3 5 7 9]


#Array Properties

In [15]:
arr=np.array([[1,2,3],[3,4,5]])

In [16]:
print(arr.shape)

(2, 3)


In [17]:
print(arr.size)

6


In [18]:
print(arr.ndim)

2


In [19]:
print(arr.dtype)

int64


#Reshaping

In [21]:
demo=np.arange(15)
print(demo)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [23]:
reshaped=demo.reshape((3,5))
print(reshaped)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [24]:
flat=reshaped.flatten()
print(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
ravel=reshaped.ravel()
print(ravel)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [29]:
transpose=reshaped.T
print(transpose)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
