<a href="https://colab.research.google.com/github/raviiraj13/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in array

0-D


In [ ]:
arr=np.array(20)
print(arr)
print(type(arr))

20
<class 'numpy.ndarray'>


In [ ]:
print(arr.ndim)

0


1-D

In [ ]:
arr=np.array([1,2,3,4,5,6,7])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6 7]
1


2-D

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
2


3-D


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[1,2,3]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
3


#Slicing

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a[0])
print(a[0][2])

[1 2 3]
3


In [ ]:
a=np.array([1,2,3,4,5,6,7])
print(a[3:6])
print(a[0::2])## if skiping one step formula is n+1 i.e 1+1=2

[4 5 6]
[1 3 5 7]


In [ ]:
td=np.array([[10,11,12,13,14],[15,16,17,18,19]])
print(td[1,1:3])

[16 17]


#Checking Datatype of Numpy Array

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [ ]:
arr=np.array(['animal','bat','cat'])
print(arr.dtype)

<U6


#Creating array with defined datatype


In [ ]:
arr=np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [ ]:
#4 byte integer
arr=np.array([1,2,3,4,5],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


#Numpy Array Shape

In [ ]:
#shape of 1D array
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.shape)

(10,)


In [ ]:
#shape of 2D Array
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


#Joining Numpy Array

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
#join 2d array
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[7,8,9]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2 3 1 2 3]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]]


#splitting Numpy Arrays

In [ ]:
#spiltting in 3 parts
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


#ravel and flatten

In [ ]:
#It converts multidimentional array into 1 dimensional array
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr.ndim)
n=arr.ravel()
print(n)
print(n.ndim)

3
[1 2 3 4 5 6 7 8 9]
1


#Unique Function

In [ ]:
k=np.array([1,2,2,2,2,7,9,4,4,4,6,6])
v=np.unique(k)
print(v)

[1 2 4 6 7 9]


In [ ]:
k=np.array([1,2,2,2,2,7,9,4,4,4,6,6])
v=np.unique(k,return_index=True)
print(v)

(array([1, 2, 4, 6, 7, 9]), array([ 0,  1,  7, 10,  5,  6]))


#Delete

In [ ]:
a=np.array([1,2,3,4,5])
v=np.delete(a,[1])
print(v)

[1 3 4 5]
