<a href="https://colab.research.google.com/github/raviiraj13/Python/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#Numpy array operation and slicing


In [4]:
arr = np.arange(1,12)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [6]:
print(arr[5:7])
print(arr[1:7])

[6 7]
[2 3 4 5 6 7]


In [7]:
print(arr[1:7:2])

[2 4 6]


In [8]:
print(arr[-5:-1])

[ 7  8  9 10]


#Selection

In [9]:
arr = np.array([1,2,3,4,5])

In [10]:
print(arr[3])

4


In [11]:
arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(arr_2d[1,2])

6


In [12]:
print(arr_2d[1])

[4 5 6]


In [13]:
print(arr_2d[:,1])

[2 5]


#Sorting

In [14]:
unsorted = np.array([5,4,26,4,56,7,5,3,5])
sorted=np.sort(unsorted)
print(sorted)

[ 3  4  4  5  5  5  7 26 56]


In [22]:
unsorted_arr_2d = np.array([[4,7,2],[3,2,1],[9,4,3]])
print(unsorted_arr_2d)
print('\n')
print(np.sort(unsorted_arr_2d,axis = 0),"\n") #sorted column wise
print(np.sort(unsorted_arr_2d,axis = 1)) #sorted row wise

[[4 7 2]
 [3 2 1]
 [9 4 3]]


[[3 2 1]
 [4 4 2]
 [9 7 3]] 

[[2 4 7]
 [1 2 3]
 [3 4 9]]


#Filter

In [24]:
nums=np.arange(21,32)
print(nums,"\n")
even_nums=nums[nums % 2 == 0]
print(even_nums)

[21 22 23 24 25 26 27 28 29 30 31] 

[22 24 26 28 30]


#Filter with mask

In [25]:
mask = nums > 24
print(nums[mask])

[25 26 27 28 29 30 31]


#fancing indexing vs np.where()

In [26]:
indices = [0,2,6]
print(nums[indices])

[21 23 27]


#Adding and removing data

In [29]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


In [40]:
a=np.array([1,2,3,4,5,6,7])
print(np.delete(a,[1,5]))
print(np.delete(a,1))

[1 3 4 5 7]
[1 3 4 5 6 7]


#Array Compatibility

In [30]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 =np.array(([7,8,9]))
print(arr1.shape == arr2.shape)

True


In [35]:
arr=np.array([[1,2,3],[4,5,6]])
new_row=([7,8,9])
new_col=([[11],[12]])
new_array_row=np.vstack((arr,new_row))
print(arr,"\n")
print(new_array_row,"\n")
new_array_col=np.hstack((arr,new_col))
print(new_array_col)

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 1  2  3 11]
 [ 4  5  6 12]]
